# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'DYZB' do
    
    pod 'Alamofire', '~> 4.0.1'
    pod 'Kingfisher', '~> 3.1.1'
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DYZB

  target 'DYZBTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DYZBUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
